### ISSUE TITLE
Naive question about structure of AST wrt Builtins

### ISSUE THREAD

**Issue by ym-han** [smucclaw/simala#1]
Right now the Simula AST represents builtins this way:

```
data Expr =
    Builtin    Builtin [Expr] 
```

```
data Builtin =
    Minus      -- ^ subtraction, arity 2
  | Divide     -- ^ (integer) division, arity 2
  | Modulo     -- ^ (integer) remainder, arity 2
  ...
```

Is it usually better to structure the AST the above way, as opposed to something like the following more naive way? I'm guessing the reason to go for the above way would be that the distinction between a BinExpr and FlexibleArityOpExr is somewhat artificial? I'm asking because I'm thinking about how to design my intermediate representation right now, but I'm guessing this would be helpful to other folks too.

```
data Expr = 
   BinExpr BinOp Expr Expr
 | FlexibleArityOpExr FlexibleArityOp [Expr] 
...
```

**Comment by kosmikus** [comment]
Separating out binary operators is totally fine. It's definitely even useful if there are many different points where you rely on there to be exactly two arguments, for example if you do some kind of optimisations and rewrites. The only reason I decided against it (for now) is that there's some run-time type checking for each of the operators anyway, and including arity-checking into this is basically no extra nuisance.
