### ISSUE TITLE
Feature request: Getting some clarity, at least in the short term, on whether we should deal with 'unknown's and how / the semantics thereof

### ISSUE THREAD

**Issue by ym-han** [smucclaw/simala#6]
I'll start by summarizing the things I've encountered that may be relevant. These may or may not turn out to be different concepts or different kinds of 'unknown'; I just haven't thought enough about it.

'Unknowns' may come up...

* In the context of inputs to a decision service: e.g., we might be using a machine learning service to try to infer what the ground terms are, but the machine learning service may not always be able to figure out what the input should be. Or perhaps it's a user who does not know what the ground term is. (In these sorts of examples, we might sometimes also have more fine-grained info, e.g. the degree of confidence or uncertainty, or a distribution over that).
* In the context of trying to (at least partially) automate the process of formalizing existing natural-language legislation/contracts/rules: this is the kind of usecase that, https://www.researchgate.net/publication/311651290_Reasoning_about_Partial_Contracts, which tries to augment CL with unknowns, was aiming to solve. (And it's quite conceivable that, down the road, we'll want to use a mix of machine learning and program synthesis methods to help with formalizing existing natural-language legislation/contracts/rules.)

The Oracle IA docs on uncertain: https://documentation.custhelp.com/euf/assets/devdocs/unversioned/IntelligentAdvisor/en/Content/Guides/Use_Intelligent_Advisor/Use_Policy_Modeling/Work_with_rules/Write_rules_logical_operators/CERTAIN_and_UNCERTAIN_operators.htm?Highlight=certain

My questions are:

* How should we handle the above sorts of issues in our semantics (if we even should)? Do we want to just have a sentinel `unknown` value, for instance, in the same way that we currently have a `undefined` term/expr in Simala?
* And on a practical level, what would be a reasonable thing to aim for _in the short term_?

@mengwong please chime in if you agree or disagree with any of this

**Comment by kosmikus** [comment]
Just to clarify: my current plan (which isn't necessarily final in any way) is to remove `undefined` and replace it with `unknown` and change the handling such that not any occurrence of `undefined` causes a crash, but that certain operations can still be computed to non-`unknown` values in the presence of `unknown`, such as e.g. `unknown || true` would yield `true`.

There are many much more ambitious options, but I think this would be an incremental improvement most likely.
